#pragma once
#include <string>

enum class Role { USER, ADMIN };

class User {
public:
    std::string username;
    std::string password_hash;
    std::string full_name;
    std::string email;
    Role role;
    bool isAutoGeneratedPwd;

    User() = default;
    User(std::string user, std::string pwd_hash, std::string name, std::string email, Role r, bool isAutoPwd);

    std::string serialize() const;
    static User deserialize(const std::string& line);
};
